### ISSUE TITLE
auto publish

### ISSUE THREAD

**Issue by MrSeaWave** [MrSeaWave/lerna-demo#5]
当使用`lerna publish`时，changlog 内容不更新，like [this](https://github.com/lerna/lerna/issues/2444) 请设定

auto publish 的`*.yml`中
```
     - name: Checkout
        uses: actions/checkout@main
        with:
          # 0 indicates all history for all branches and tags.
          fetch-depth: '0'
```
